//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP.MVP.ServicioValor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValorDataContract", Namespace="http://schemas.datacontract.org/2004/07/GP.ServicioBase.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ValorDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DeshabilitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short InfluenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Deshabilitado {
            get {
                return this.DeshabilitadoField;
            }
            set {
                if ((this.DeshabilitadoField.Equals(value) != true)) {
                    this.DeshabilitadoField = value;
                    this.RaisePropertyChanged("Deshabilitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Influencia {
            get {
                return this.InfluenciaField;
            }
            set {
                if ((this.InfluenciaField.Equals(value) != true)) {
                    this.InfluenciaField = value;
                    this.RaisePropertyChanged("Influencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ValorId {
            get {
                return this.ValorIdField;
            }
            set {
                if ((this.ValorIdField.Equals(value) != true)) {
                    this.ValorIdField = value;
                    this.RaisePropertyChanged("ValorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioValor.IServicioValor")]
    public interface IServicioValor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioValor/Save", ReplyAction="http://tempuri.org/IServicioValor/SaveResponse")]
        void Save(GP.MVP.ServicioValor.ValorDataContract entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioValor/Save", ReplyAction="http://tempuri.org/IServicioValor/SaveResponse")]
        System.Threading.Tasks.Task SaveAsync(GP.MVP.ServicioValor.ValorDataContract entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioValor/Edit", ReplyAction="http://tempuri.org/IServicioValor/EditResponse")]
        void Edit(GP.MVP.ServicioValor.ValorDataContract entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioValor/Edit", ReplyAction="http://tempuri.org/IServicioValor/EditResponse")]
        System.Threading.Tasks.Task EditAsync(GP.MVP.ServicioValor.ValorDataContract entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioValor/Enable", ReplyAction="http://tempuri.org/IServicioValor/EnableResponse")]
        void Enable(GP.MVP.ServicioValor.ValorDataContract entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioValor/Enable", ReplyAction="http://tempuri.org/IServicioValor/EnableResponse")]
        System.Threading.Tasks.Task EnableAsync(GP.MVP.ServicioValor.ValorDataContract entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioValor/Disable", ReplyAction="http://tempuri.org/IServicioValor/DisableResponse")]
        void Disable(GP.MVP.ServicioValor.ValorDataContract entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioValor/Disable", ReplyAction="http://tempuri.org/IServicioValor/DisableResponse")]
        System.Threading.Tasks.Task DisableAsync(GP.MVP.ServicioValor.ValorDataContract entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioValor/ObtainId", ReplyAction="http://tempuri.org/IServicioValor/ObtainIdResponse")]
        GP.MVP.ServicioValor.ValorDataContract ObtainId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioValor/ObtainId", ReplyAction="http://tempuri.org/IServicioValor/ObtainIdResponse")]
        System.Threading.Tasks.Task<GP.MVP.ServicioValor.ValorDataContract> ObtainIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioValor/ObtainAll", ReplyAction="http://tempuri.org/IServicioValor/ObtainAllResponse")]
        GP.MVP.ServicioValor.ValorDataContract[] ObtainAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioValor/ObtainAll", ReplyAction="http://tempuri.org/IServicioValor/ObtainAllResponse")]
        System.Threading.Tasks.Task<GP.MVP.ServicioValor.ValorDataContract[]> ObtainAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioValorChannel : GP.MVP.ServicioValor.IServicioValor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioValorClient : System.ServiceModel.ClientBase<GP.MVP.ServicioValor.IServicioValor>, GP.MVP.ServicioValor.IServicioValor {
        
        public ServicioValorClient() {
        }
        
        public ServicioValorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioValorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioValorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioValorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Save(GP.MVP.ServicioValor.ValorDataContract entity) {
            base.Channel.Save(entity);
        }
        
        public System.Threading.Tasks.Task SaveAsync(GP.MVP.ServicioValor.ValorDataContract entity) {
            return base.Channel.SaveAsync(entity);
        }
        
        public void Edit(GP.MVP.ServicioValor.ValorDataContract entity) {
            base.Channel.Edit(entity);
        }
        
        public System.Threading.Tasks.Task EditAsync(GP.MVP.ServicioValor.ValorDataContract entity) {
            return base.Channel.EditAsync(entity);
        }
        
        public void Enable(GP.MVP.ServicioValor.ValorDataContract entity) {
            base.Channel.Enable(entity);
        }
        
        public System.Threading.Tasks.Task EnableAsync(GP.MVP.ServicioValor.ValorDataContract entity) {
            return base.Channel.EnableAsync(entity);
        }
        
        public void Disable(GP.MVP.ServicioValor.ValorDataContract entity) {
            base.Channel.Disable(entity);
        }
        
        public System.Threading.Tasks.Task DisableAsync(GP.MVP.ServicioValor.ValorDataContract entity) {
            return base.Channel.DisableAsync(entity);
        }
        
        public GP.MVP.ServicioValor.ValorDataContract ObtainId(int id) {
            return base.Channel.ObtainId(id);
        }
        
        public System.Threading.Tasks.Task<GP.MVP.ServicioValor.ValorDataContract> ObtainIdAsync(int id) {
            return base.Channel.ObtainIdAsync(id);
        }
        
        public GP.MVP.ServicioValor.ValorDataContract[] ObtainAll() {
            return base.Channel.ObtainAll();
        }
        
        public System.Threading.Tasks.Task<GP.MVP.ServicioValor.ValorDataContract[]> ObtainAllAsync() {
            return base.Channel.ObtainAllAsync();
        }
    }
}
